# Generated by Django 5.1 on 2024-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_drf', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
